title: Monisha
description: Lead Technical Writer
url: "https://monishas9011.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Monisha"
  bio: "10 years turning complexity into clarity — and making products make sense."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/monisha-shanka-writer3421/"

minimal_mistakes_skin: "default"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
